<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
    <PackageReference Include="Orcamentaria.Lib.Application" Version="1.5.4" />
    <PackageReference Include="Orcamentaria.Lib.Domain" Version="9.4.1" />
    <PackageReference Include="Orcamentaria.Lib.Infrastructure" Version="4.3.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.2" />
	<PackageReference Include="RabbitMQ" Version="3.6.2" />
	<PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orcamentaria.LogService.Application\Orcamentaria.LogService.Application.csproj" />
    <ProjectReference Include="..\Orcamentaria.LogService.Infrastructure\Orcamentaria.LogService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
